# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

services:
    campaignchain.hook.campaignchain.duration:
        class: CampaignChain\Hook\DurationBundle\EntityService\DurationService
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
    campaignchain.hook.form.type.campaignchain.duration:
        class: CampaignChain\Hook\DurationBundle\Form\Type\DurationType
        arguments: [ @service_container ]
    campaignchain.hook.listener.campaignchain.duration:
        class: CampaignChain\Hook\DurationBundle\EventListener\DurationListener
        arguments: [ @service_container ]